### ISSUE TITLE
"EventQueue size exceeded" exception

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#103]
I'm trying to build a large RAM component from smaller building blocks and eventually the simulator hits an "EventQueue size exceeded" exception.

Once this happens the editor goes into a bad state, failing to draw new components and (perhaps) even save the existing work.

I suppose this limit might exist to keep the simulation contained; if that is the case, perhaps the error should be handled in a graceful way so the circuit doesn't get wasted.

Alternatively, we could increase the limit of this queue or make it configurable on a per project basis.

For a repro, see this circuit: https://circuitverse.org/users/1935/projects/4774
In the 16KB circuit (which is incomplete) I'm trying to add another 4KB circuit; doing so causes the exception.

**Comment by satu0king** [comment]
Wow, I wasn't expecting this to happen for a long while. The current simulation queue is limited to 10000 elements because the priority queue data structure uses linear implementation instead of `logn` implementation. We need to change the implementation of the priorty queue to use a heap data structure instead of a linear datastructure.

**Comment by fpintos** [comment]
Well, I suppose the new built-in RAM component will mitigate this problem.

**Comment by CEa-TIde** [comment]
I've run in this error aswell while building a 8-bit computer. I can't access it anymore as it stays in a loading state. Even if you remove the loading icon, "main" isn't visible/accessable. It is quite crucial for me that this gets fixed, as the project is of importance for school.
Project: https://circuitverse.org/users/13948/projects/41310

The linked issue is still open, so is there a quick fix that can happen, like increasing the element limit, until it's fixed properly?

**Comment by Palaksharma23** [comment]
I would love to take up this issue

**Comment by pulkit-30** [comment]
Hey @tachyons @gr455,
I would like to continue with this issue, 
Can we discuss the implementation of this...?

Thanks

**Comment by gr455** [comment]
@pulkit-30 I believe this issue was fixed in https://github.com/CircuitVerse/CircuitVerse/pull/2356. Can you verify?

**Comment by pulkit-30** [comment]
Hey @gr455,
I verified this issue with the [mentioned](https://circuitverse.org/users/1935/projects/4774) circuit on the local development... 
Yes, this issue is still valid

https://user-images.githubusercontent.com/76155456/156405209-d2b8d880-9c08-4475-b86e-ad04411f5bad.mov

I am redrawing the circuit on the simulator and trying to add another 4KB circuit;
let me know if I am doing something wrong

**Comment by pulkit-30** [comment]
Hey @gr455, please check this issue...
Thanks :D

**Comment by gr455** [comment]
> Hey @gr455, I verified this issue with the [mentioned](https://circuitverse.org/users/1935/projects/4774) circuit on the local development... Yes, this issue is still valid
> 
>  Screen.Recording.2022-03-02.at.9.58.57.PM.mov 
> I am redrawing the circuit on the simulator(copy and paste) and trying to add another 4KB circuit; let me know if I am doing something wrong

Aw man :disappointed: . It would be great if you could try your hand at it

**Comment by pulkit-30** [comment]
No problem, I will try to solve this 👍🏽
