### ISSUE TITLE
🐞 Bug : Nav bar is not responsive in mobile version 

### ISSUE THREAD

**Issue by Saipradyumnagoud** [CircuitVerse/CircuitVerse#5226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the mobile view the nav bar is not working properly it is not responsive . when we press the [X] button the nav bar is not getting closed

![image](https://github.com/user-attachments/assets/00ed9e76-4b17-4f8b-a8dd-95077eddcf87)

![image](https://github.com/user-attachments/assets/bb8ed229-3a26-4c5e-9bd1-e80505013664)

### Steps To Reproduce

1. go to the web page in mobile
2. Now press the nav bar her you can see it will open but it i will not close 
3. Here you can see the problem

### Expected Behavior

when we press the [X] button the nav bar should disappear

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Saipradyumnagoud** [comment]
@salmoneatenbybear can you please assign me the issue so that i can raise the pullrequest

**Comment by salmoneatenbybear** [comment]
@Saipradyumnagoud this has been addressed and fixed in #5203. 

@tachyons please could you close this issue if you get time

**Comment by Saipradyumnagoud** [comment]
@salmoneatenbybear I think the issue did not solve yet please you can see once

**Comment by salmoneatenbybear** [comment]
@Saipradyumnagoud it has solved the bug the prod version is just not built again

**Comment by salmoneatenbybear** [comment]
@Saipradyumnagoud once we deploy the new changes it will be fixed

**Comment by Saipradyumnagoud** [comment]
okay @salmoneatenbybear
